#!/bin/bash

# Christopher Del Fattore

usage() {
echo " ytj command line options:"
echo " -h: display a usage statement (also displayed if ytj is called with no arguments)"
echo " -k: keep downloaded video files (default behavior is to delete all downloaded flv files after they have been played."
#echo " -l: (Optional) (I'm feeling *l*ucky) download and play only the first search result."

}



#store the search term in a file
echo $1 > file;

# replace the spaces if any with + (plus signs)
addplus=`sed 's/  */+/g' file`;

vid_directory=`sed -e "s/  */_/g" -e "s/'//g" file`;

mkdir -m +rwx $vid_directory;

# remove the tempary file called file
rm file;

wget -O ytj.results  "http://www.youtube.com/results?search_query=$addplus%2C+video&lclk=video";

#Find the links to the videos in result.html and download the videos
#use grep with the following unique regular expression
#this regular expression only takes the lines with the links to the videos that match our
#search results, this regular expressions excludes featured videos and similar videos

grep '<div class="yt-lockup-thumbnail"><a href="/watch?v=' ytj.results |

#now use sed commands to get ride of the html text beside the link we want
#first use this sed to remove most of the html before the link we need

sed 's/<div  id=""  class="yt-uix-tile yt-lockup-list yt-tile-default yt-grid-box "><div class="yt-lockup-thumbnail">//g' |

#more sed needed, little by little i will have the link to the url of each video

sed 's/class="ux-thumb-wrap yt-uix-sessionlink yt-uix-contextlink contains-addto result-item-thumb"//g' |

# more

sed 's/<span class="video-thumb ux-thumb yt-thumb-default-185 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner">//g' |

# you guessed it more!

sed 's/data-sessionlink=".*"><img src="http:\/\/.*<\/span>//g' |

# breakthrough almost done

sed 's/ *data-sessionlink="ved=.*&amp;ei=.*><img.*alt=.*><span class="vertical-align"><\/span><\/span><\/span><\/span><span class="video-time">.*<\/span>//g' |

# last few

sed 's/<a href="\///g' |

sed 's/"//g' | sed 's/^  *//g' | sed 's/$\n//g' > links;

#get the titles of the videos

# time to download the videos and play the audio
ID=`cat ~/ytj-git/links`

for line in $ID
do
cclive -O $vid_directory/$line "http://www.youtube.com/$line" &
done

for line in $ID
do
mplayer -vo null $line
done


#remove any existing temporary files
rm ytj.results;
rm -r $vid_directory 
